### ISSUE TITLE
How does an external feature affect the ranking?

### ISSUE THREAD

**Issue by MickaelBZH** [bloomberg/lucene-solr#181]
Hi,

There is something I don't really understand after reading the readme about the external feature:

 {
   "name" : "userFromMobile",
   "class" : "org.apache.solr.ltr.feature.ValueFeature",
   "params" : { "value" : "${userFromMobile}", "required":true }
 }

How can userFromMobile affect the ranking? It does affect the score according its weight, but it's for all documents ... so how is it supposed to affect the ranking? Did I miss something?

**Comment by mnilsson23** [comment]
There's roughly three categories of features you can use.
- Document only: These are properties of a document alone which affect ranking.  A good example of this could be document popularity or length.

- Context only: These are features that are dependent only on the environment.  Examples of these could be user classification, location, or even device, like the feature you mentioned above.  While these types of features could affect your documents in the same way, they would yield different or more personalized results for the exact same query.  If you wanted, instead of training 1 global model to make decisions based on these features (say for mobile, and desktop), you could train N models, one per context combination, and then just select the appropriate one.

- Context + Document: These are features in which the context affects individual documents in your result set differently.  An example of this is the term frequencies of your query in each matching document.  The line between context and context + document can be kind of blurry, but either way you pass the required information through the efi params when using the plugin.

If you were to train a non-linear model like LambdaMART, maybe it would detect that searches on mobile tend to prefer mobile enabled websites higher up, but on desktop maybe it doesn't matter.
Does that help answer your question @MickaelBZH?

**Comment by MickaelBZH** [comment]
Thanks for the reply @mnilsson23 
My question is more about how one "context only" feature affects the ranking if it's dependent only on the environment and not on the document.

If I define only one external feature userFromMobile and if I train a model with the following data:

query|docID|userFromMobile|has_clicked|CLICK_LOG

Will the docID somehow be taken into consideration? And how? Because I will end up with something like:

```
{
    "class":"org.apache.solr.ltr.model.LinearModel",
    "name":"myModelName",
    "features":[
        { "name": "userFromMobile"}
    ],
    "params":{
        "weights": {
            "userFromMobile": 5.0
        }
    }
}



```

**Comment by diegoceccarelli** [comment]
@MickaelBZH Thanks for your question, the model will not learn about a particular `docID`, but you can have a feature `isMostClicked` . As example, you could store in a database table, the couple `docID, number of clicks from mobile` , and then at query time, check if the number of clicks is greater than a threshold (or using the number of clicks as a feature!), your training data at that point will be:

`query|docID|userFromMobile|**isMostClicked**|has_clicked|CLICK_LOG`

where `**isMostClicked**` will measure if at the moment of the interaction the document had a large number of clicks. In this way you will learn how to boost documents that you've been the most clicked if the user was from mobile for a specific query (although I'll be careful because you could return only old documents :)).   Note: you could also store the number of clicks from non mobile devices and then have a feature that compares those numbers (e.g., `number of clicks from mobile` / `number of clicks from other devices`) 
Please let us know if that helps :)

**Comment by diegoceccarelli** [comment]
@MickaelBZH I hope my response replied to your questions, I'm going to close this issue, if you still have questions please do not hesitate to write an email to the [Solr mailing list](http://lucene.apache.org/solr/resources.html)

Thanks, Diego
