### ISSUE TITLE
Sparse Efi Feature Support where no default

### ISSUE THREAD

**Issue by alessandrobenedetti** [bloomberg/lucene-solr#9]
Related the sparse efi support this is mainly for categorical features encoded in binaries features.
Based on the different observations per category we could end up in a lot of binaries feature.
Instead of passing and caching all of them ( even the one that are actually 0) I propose to avoid the scoring for the null features.

When evaluating the model their value will be 0.
This can have some implications as we know that in Information Theory null != 0/"" in most the cases.

It will have impact mainly on the lambdaMART model, which at the moment will consider a null feature the same of a feature with value 0.

**Comment by mnilsson23** [comment]
Hey Alessandro, I wanted to clarify a couple points that you brought up.  
`I propose to avoid the scoring for the null features.`
Currently the SparseModelScorer uses a priority queue, which ensures that only features which advance to the current doc are scored, and those that dont (which means they don't apply) are not scored.

Are you specifically talking about the ValueFeature (which is probably the one you use for efi values), which returns a provided value for all docs?  If so then yes, it currently doesn't skip any docs since it uses the MatchAllIterator, and advances to every one it is told to jump to, returning its value.  This could be improved to take into accout if the value it needs to return is "null" and instead just skip all docs, preventing a score() call.

In terms of lambdaMART evaluating a discreet feature value as 0, 1, or "null", I don't think that is typically a good thing to do, since it can only evaluate to go down the left or right path.  If you really wanted to check "isApplicable" you probably would need a different discreet feature for that, which would add extra depth to your trees.  However, correct me if I'm wrong, but I think you may be alluding to the fact that the ModelWeight keeps all the feature values in a `float[] modelFeatureValuesNormalized`.  And any features that are "skipped" just get a default value of 0 in that array.  If instead you think that this should be a sparse map then I agree that it could be changed, so long as there are measured performance metrics showing that the sparse map performs better than the dense array.  My guess is that both will perform better than each other in their respective dense/sparse feature situations, so we probably would want to support both.

**Comment by alessandrobenedetti** [comment]
hi Michael,
let me answer inline :

> Are you specifically talking about the ValueFeature (which is probably the one you use for efi values), which returns a provided value for all docs? If so then yes, it currently doesn't skip any docs since it uses the MatchAllIterator, and advances to every one it is told to jump to, returning its value. This could be improved to take into accout if the value it needs to return is "null" and instead just skip all docs, preventing a score() call.

Yes Michael, I was talking about those feature, but actually this can be applied to all the features that take an efi in input.
Even a SolrFeature, which takes in input an efi as a query parameter for example, if we don't pass the efi, I guess we should not score at all that feature.
I will investigate a little bit more tomorrow, and update the ticket.

> However, correct me if I'm wrong, but I think you may be alluding to the fact that the ModelWeight keeps all the feature values in a float[] modelFeatureValuesNormalized. And any features that are "skipped" just get a default value of 0 in that array. 

I was exactly referring to that, I don't have any plan at the moment, but I agree with your considerations about that completely.
In particular I agree as well that you need first to model the "null" value at training time, and this will be reflected at query time.
I will update the ticket tomorrow.

Cheers

**Comment by alessandrobenedetti** [comment]
https://github.com/bloomberg/lucene-solr/pull/17

**Comment by alessandrobenedetti** [comment]
Merged !
